# Nginx Dockerfile
FROM nginx:alpine

# Удаляем дефолтную конфигурацию
RUN rm /etc/nginx/conf.d/default.conf

# Копируем нашу конфигурацию
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

# Порт nginx
EXPOSE 80

# Healthcheck
CMD ["nginx", "-g", "daemon off;"]
