# Generated by Django 5.0.6 on 2026-03-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="ads_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Объявлений"),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="Аватар"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, max_length=500, verbose_name="О себе"),
        ),
        migrations.AddField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Подтверждён"),
        ),
        migrations.AddField(
            model_name="profile",
            name="member_since",
            field=models.DateTimeField(blank=True, null=True, verbose_name="С даты"),
        ),
        migrations.AddField(
            model_name="profile",
            name="rating",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=3, verbose_name="Рейтинг"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="reviews_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Отзывов"),
        ),
    ]
