# Generated by Django 5.0.6 on 2026-03-30 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_options_alter_adimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='city',
            field=models.ForeignKey(
                blank=True,
                help_text='Выберите город из списка или введите свой',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='ads.city',
                verbose_name='Город'
            ),
        ),
    ]
