# Generated by Django 5.0.6 on 2026-04-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0004_ad_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="deposit_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Залог",
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="min_rental_days",
            field=models.PositiveIntegerField(
                blank=True, default=1, verbose_name="Мин. срок аренды (дней)"
            ),
        ),
    ]
